title: RocketDriver Pro
show_logo: true
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal

version: '2.0.0810'
build: '2023.08.10'

author:
  name: XUZHUOXI
  home_page_url: https://www.xuzhuoxi.com/

unity:
  package_url: https://assetstore.unity.com/packages/slug/234202
  publisher_url: https://assetstore.unity.com/publishers/74539

home:
  url: https://www.xuzhuoxi.com/RocketDriver-Docs

github:
  issues_url: https://github.com/xuzhuoxi/RocketDriver-Docs/issues
  issues_new_url: https://github.com/xuzhuoxi/RocketDriver-Docs/issues/new
  
formspree_form_path : 'f/mpznbjpa'